### ISSUE TITLE
creditcard format issue

### ISSUE THREAD

**Issue by Hardiktspaceo** [wirecard/paymentSDK-iOS#1]
In download demo. in simple Target i check that demo but for credit card format it accept unlimited number and try to figure out to solve that but i am not able to find please solve that issue help me a lot.

**Comment by stefan-sedlak** [comment]
Hi,
thanks for your idea. It will not be included in next release, but it will be implemented.

**Comment by stefan-sedlak** [comment]
Hi @Hardiktspaceo,
please check release [2.7.0](https://github.com/wirecard/paymentSDK-iOS/releases/tag/2.7.0)
and close the issue if you are fine with the solution.
Best,
Stefan

**Comment by stefan-sedlak** [comment]
According no feedback, I close the issue. Please create new one/reopen if it is needed.
