### ISSUE TITLE
WirecardPaymentResponse.getCard() == nil

### ISSUE THREAD

**Issue by leonidaas** [wirecard/paymentSDK-iOS#13]
we need to get the cardtype of the credit card but somehow WirecardPaymentResponse.getCard() is always null

is this a known issue?

is there another way to get the creditcard institution?

**Comment by stefan-sedlak** [comment]
Hi @leonidaas ,
by default gateway does not provide card data in response.
You can ask merchant support to change your merchant account configuration.
