### ISSUE TITLE
[NSBundle initWithURL] nil URL argument

### ISSUE THREAD

**Issue by JoaoRSilverio** [wirecard/paymentSDK-iOS#14]
Hi I'm trying to build a Native Module in swift for your IOS paymentSDK but when calling .make() method of a WDECClient instance I get a crash with a NSInvalidArgumentException *** [NS Bundle initWithURL] nil URL argument ***
I pass as argument a CreditCardPayment instance and a function with WDECPaymentResponse and Error  as nullable arguments

I installed the sdk via cocoaPods and i checked that the client is created by inspecting a break-point.
Do you have any idea why such exception might be thrown ? 
In the copy Pods Resources section in build Phases all the bundles seem to be listed.

`self.client = WDECClient.init(environment: WDECEnvironment.TEST)!; // I initiate the client`
`let payment = WDECCardPayment()
   payment.amount = NSDecimalNumber(integerLiteral: 10)
   payment.currency = "USD"
   payment.transactionType = WDECTransactionType.purchase // add payment data`
`payment = self.helperGeneratePaymentSignature(merchantAccountID: MERC_ACCOUNT_ID, payment: payment, merchantSecret: SECRET_KEY) // add signature`

`self.client!.make(payment, withCompletion: self.onResult) //execute the payment`
here is self.onResult signature
`func onResult(response:WDECPaymentResponse?, error:Error?)`

Thank you for your time, any help is appreciated

**Comment by PaymentSDK** [comment]
Hi Joao,

what is the SDK version?

**Comment by JoaoRSilverio** [comment]
The SDK version is 3.1.0 , and theres no WDeCom.bundle or WDeComCard.bundle in derived data.

**Comment by JoaoRSilverio** [comment]
Good news I solved it!
Thank you for your answer after realizing that the bundle wasn't being copied although being listed in Copy Pods Resources I found the solution here [here](https://github.com/CocoaPods/CocoaPods/issues/7823#issuecomment-397522298) I deleted Copy Pods Resources and did a pod install and it now works.

**Comment by PaymentSDK** [comment]
Happy to hear that.
