### ISSUE TITLE
Tokenization impossible

### ISSUE THREAD

**Issue by Radu12451** [wirecard/paymentSDK-iOS#15]
Hello,

I'm trying to tokenize a card using SDK 3.2.0 and I can't get the card token from the response class. (I found absolutely no documentation for this SDK version). I also tried on version 2.16.0 and I'm getting a network issue. 

```
 self.client!.make(payment, withCompletion:{(response: WDECPaymentResponse?,error: Error?) in
                //here - how can I get CardToken
let alertTitle = error != nil ? "Error" : "Success"
                let alertMessage = error != nil ? error!.localizedDescription : "Item(s) has been purchased."
                let ac = UIAlertController(title: alertTitle, message: alertMessage, preferredStyle: .actionSheet)
                
                ac.addAction(UIAlertAction(title:"OK", style:.default, handler:nil));
                self.present(ac, animated:true, completion:nil)
            })
```

**Comment by stefan-sedlak** [comment]
Hi @Radu12451 ,
integration doc: http://wirecard.github.io/paymentSDK-iOS/integration/3.2.0/
API reference: http://wirecard.github.io/paymentSDK-iOS/api/3.2.0/

You are interested in class http://wirecard.github.io/paymentSDK-iOS/api/3.2.0/Classes/WDECCardPaymentResponse.html

It is returned as response in completion block for all card transactions.
I advise to use Instant Payment Notifications (from gateway to your backend server) and do not rely on responses from mobile paymentSDK as mobile devices are unreliable (battery, network, ...)
Responses from SDK are OK for UX but backed shall not rely on them.

**Comment by Radu12451** [comment]
Hello @stefan-sedlak ,

The class that I am interested in is "WDECPaymentResponse" - notice the missing "C". That class is used in the example. I will try using the one in your answer and get back to you. 

Thanks for your help.

**Comment by Radu12451** [comment]
Hello @stefan-sedlak,

It works by casting "WDECPaymentResponse" to "WDECCardPaymentResponse" in the response block. 

Thanks,
