### ISSUE TITLE
Can't key 4 digit for cvv in WDECAnimatedCardFieldScannerGallery

### ISSUE THREAD

**Issue by NayOoLinn** [wirecard/paymentSDK-iOS#17]
In iOS sdk, i am trying to  key in 4 digit cvv for amex card and cvv is allowed only 3 digit in WDECAnimatedCardFieldScannerGallery....  Can anyone help with that..? Thanks!!

**Comment by stefan-sedlak** [comment]
Hi @NayOoLinn ,
could you please provide SDK version?
Meanwhile we will verify the most recent version.

We will provide quick fix if needed.

Thanks,
Stefan

**Comment by NayOoLinn** [comment]
SDK version is 3.4.0..
Really appreciate if you can make quick fix.. 👍 
Thanks a lot!!

**Comment by stefan-sedlak** [comment]
Hi @NayOoLinn ,
the issue is valid. we will fix it asap. we are corporate but we will try our best ❤️ 
Meanwhile you can use non-animated layout for integration testing.
Non-animated layout is not affected.
Best,
Stefan

**Comment by stefan-sedlak** [comment]
Hi @NayOoLinn please verify v3.4.1
Best,
Stefan

**Comment by NayOoLinn** [comment]
Thanks a lot.. it's working Great!! 👍
