### ISSUE TITLE
How to get card holder name from WDECAnimatedCardFieldScannerGallery?

### ISSUE THREAD

**Issue by NayOoLinn** [wirecard/paymentSDK-iOS#18]
I'm sdk version of 3.4.1...
I can't access firstName and lastName which user typed inside WDECAnimatedCardFieldScannerGallery... 
The sdk needs first name and last name when using "authorization"...
Thanks!!

**Comment by stefan-sedlak** [comment]
Hi @NayOoLinn ,
it shall be accessible via [accountHolder](https://wirecard.github.io/paymentSDK-iOS/api/latest/Classes/WDECPayment.html#//api/name/accountHolder) property. It is mapped to [lastName](http://wirecard.github.io/paymentSDK-iOS/api/latest/Classes/WDECCustomerData.html#//api/name/lastName).
Best,
Stefan

**Comment by NayOoLinn** [comment]
Hi Setfan,
I tried to access accountHolder property but it's NIL(uninitialized) ..
could you please check..? Thanks!.

**Comment by stefan-sedlak** [comment]
I checked it on device (build with scanner and gallery) few minutes ago.
it is strange. could you please share your code snippet?

**Comment by NayOoLinn** [comment]
Here is the code -> 

//after user typed in all info
//cardField is WDECAnimatedCardFieldScannerGallery

//create payment
let payment = WDECCardPayment()
payment.amount = 1
payment.currency = "SGD"
payment.transactionType = .authorization//.authorizationOnly//.tokenize//

payment.merchantAccountID = merchanteId
payment.requestID = cardRegRef
payment.signature = signature

let accountHolder = WDECCustomerData()
accountHolder.firstName = cardField.cardPayment.accountHolder?.firstName
accountHolder.lastName = cardField.cardPayment.accountHolder?.lastName
payment.accountHolder = accountHolder
//cardField.cardPayment.accountHolder return nil in above code

**Comment by stefan-sedlak** [comment]
Hi @NayOoLinn 
I see a confusing [lines](https://github.com/wirecard/paymentSDK-iOS/blob/e892773bbedb6fdd348ab64237c5bd1ac2be5bd7/Example-Swift/Embedded/AnimatedCardfieldVC.swift#L83-L86) in Swift example app. please remove your lines:
```Swift
let accountHolder = WDECCustomerData()
accountHolder.firstName = cardField.cardPayment.accountHolder?.firstName
accountHolder.lastName = cardField.cardPayment.accountHolder?.lastName
payment.accountHolder = accountHolder
```

**Comment by NayOoLinn** [comment]
Hi Stefan,
Without accountHolder, the authorization will fail with 400 bad request...
I've tested with hardcode firstName and lastName.. And it's working..

**Comment by NayOoLinn** [comment]
Sorry,
Without accountHolder, the authorization return the following error->
<status code="400.1022" description="The Parent Transaction Id was not successful, the operation is not possible.  Please do not try again." severity="error" />

**Comment by NayOoLinn** [comment]
<status code="400.1022" description="The Parent Transaction Id was not successful, the operation is not possible.  Please do not try again." severity="error" />

**Comment by NayOoLinn** [comment]
Sorry Stefan,
Without accountHolder, the authorization will return the following ->

```
<statuses>
<status code="400.1022" description="The Parent Transaction Id was not successful, the operation is not possible.  Please do not try again." severity="error" />
</statuses>
```

**Comment by stefan-sedlak** [comment]
Hi @NayOoLinn , are you available for GoToMeeting call now?
I can call you.

**Comment by NayOoLinn** [comment]
Hi Sefan,
Really appreciate your help..
How about Monday 11:00 am GMT+6:30..?
And how should we make a call skipe?

**Comment by stefan-sedlak** [comment]
I have very bad experience with Skype (for Business) on macOS.
11:00 am GMT+6:30 is 6:30 am CEST I walk with my dog in morning 😄 
You can join GTM via web I will send a link later.
What about 12:30 pm MMT / 8:00 am CEST ?

**Comment by NayOoLinn** [comment]
Cool!! 12:30 pm MMT is fine..
See you and Thanks!..

**Comment by NayOoLinn** [comment]
Hi @stefan-sedlak ,
I'm ready for the call.. 😄

**Comment by stefan-sedlak** [comment]
Hi @NayOoLinn 
https://global.gotomeeting.com/join/701451357
