### ISSUE TITLE
Wrong dependency tree in Podfile.lock

### ISSUE THREAD

**Issue by Gray-Wind** [wirecard/paymentSDK-iOS#19]
Hi, I'm trying to take a look at Swift Example, first of all I need to install dependencies. It fails with the next error:

```
Example-Swift❯ pod install
Analyzing dependencies
Fetching podspec for `paymentSDK` from `..`
[!] CocoaPods could not find compatible versions for pod "libextobjc/EXTScope":
  In snapshot (Podfile.lock):
    libextobjc/EXTScope (= 0.6, ~> 0.6)

  In Podfile:
    paymentSDK/All (from `..`) was resolved to 3.4.1, which depends on
      paymentSDK/Core (= 3.4.1) was resolved to 3.4.1, which depends on
        libextobjc/EXTScope (~> 0.4.1)

It seems like you've changed the constraints of dependency `libextobjc/EXTScope` inside your development pod `paymentSDK/All`.
You should run `pod update libextobjc/EXTScope` to apply changes you've made.
```

BTW the same problem is with ObjC sample.

**Comment by stefan-sedlak** [comment]
Hi @Gray-Wind ,

You can delete `Podfile.lock` file(s) and run `pod install`.
`paymentSDK.podspec` was not correctly regenerated
and we unintentionally downgraded libextobjc dependency.
It does not cause any issue,
so we will fix paymentSDK.podspec (upgrde all dependencies versions) with next release.

Thanks,
Stefan

**Comment by Gray-Wind** [comment]
Hi @stefan-sedlak ,

For sure I can do it, but there should be a whole reason to have `lock` file in repo, shouldn't be?

**Comment by stefan-sedlak** [comment]
Hi @Gray-Wind ,
sure there is a reason. It was tested with locked dependencies versions.
It shall work with overriding `lock` file because there are no breaking changes in `libextobjc` according [semantic versioning](https://semver.org/).
Best,
Stefan

**Comment by Gray-Wind** [comment]
So I believe, `lock` files here should be updated to reflect last changes.
