### ISSUE TITLE
Separate Card number, CVC and Exp. Date from WDCardField

### ISSUE THREAD

**Issue by bgoss** [wirecard/paymentSDK-iOS#2]
WD could provide a WDCardNumberField, WDCVCField, and WDExpirationDateField separately.
None of the data (card number, CVC or Expiration Date) would have to be exposed to the developer, however, developers could layout each field individually instead of only the group of all 3 fields combined.

**Comment by stefan-sedlak** [comment]
Hi, it is a good idea, but we need consider consequences. I will keep the issue opened and let you know result ASAP.

**Comment by stefan-sedlak** [comment]
Hi @bgoss , we will not implement it in the end... there are always bigger topics in backlog.
