### ISSUE TITLE
It is not possible to set notification format

### ISSUE THREAD

**Issue by sergeikretov** [wirecard/paymentSDK-iOS#21]
Currently, one can set Transaction State and notification URL, but setting up notification format e.g. to **application/json-signed** is not possible. 

Correct me, if I am wrong. Please add this possibility.

**Comment by stefan-sedlak** [comment]
Hi @sergeikretov , you are right at the moment notification format is not configurable in SDK.
But you can ask merchant support to configure IPN format in merchant account configuration (gateway side).
Best,
Stefan

**Comment by stefan-sedlak** [comment]
Hi @sergeikretov ,
We will add this option to 3.x branch but it will not be added quickly.
Best,
Stefan

**Comment by sergeikretov** [comment]
May be, you can also point us to the correct testing flow of notifications (IPNs), as currently we are actively working on integration with Wirecard and want to get all payment transactions notifications to our webhook URL. And the issue is that, if we do not set notification format to **application/json-signed**, then we get pure, unsigned XML in notification message that we can not trust. This all happens currently with test merchants found in documentation.

https://doc.wirecard.com/GeneralPlatformFeatures_IPN.html
https://doc.wirecard.com/CreditCard.html#CreditCard_TestCredentials

**Comment by stefan-sedlak** [comment]
I see you use generic test merchant account.
Please ask merchant support to provide you dedicated test account with IPN configuration.
At the moment we can not provide quicker solution.

What SDK version do you use?

**Comment by sergeikretov** [comment]
> What SDK version do you use?
If I am not mistaking, then:
3.3.1 android
3.3.0 ios

we will try to get to merchant support for test account.

**Comment by stefan-sedlak** [comment]
We will implement the request in 3.x versions. I added the feature to backlog.
It will take a time as we focus on different topics and a solution is available.
I cannot commit any due date.
Best,
Stefan

**Comment by sergeikretov** [comment]
thank you and looking forward to having this feature. will try to use the solution you suggested, but currently no response from support yet.
