### ISSUE TITLE
Can't install paymentSDK version 3.5.0

### ISSUE THREAD

**Issue by NayOoLinn** [wirecard/paymentSDK-iOS#22]
I've installed paymentSDK version 3.4.1 and I'm trying to update to 3.5.0.. I got the following error when i run pod install

`
[!] CocoaPods could not find compatible versions for pod "paymentSDK":
  In Podfile:
    paymentSDK (~> 3.5.0)

None of your spec sources contain a spec satisfying the dependency: `paymentSDK (~> 3.5.0)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default.
`

I've already tried **pod repo update** and **pod install --repo-update** .... but still having the above error..

**Comment by PeterStavny** [comment]
Hi @NayOoLinn ,
I checked it in Cocopods and you are right. We updated the podspec and required code a few minutes ago. The issue had solved. Please try to install/update pods again.
 
Our apologies and Thanks for your feedback!

**Comment by NayOoLinn** [comment]
Thanks a lot..! It works now.. Cheers.!!
