### ISSUE TITLE
Only tokenise card without making a payment

### ISSUE THREAD

**Issue by yfujiki** [wirecard/paymentSDK-iOS#23]
I don't see a method to only tokenise the card without making a payment. 

In our app, the UI just provides interface of saving credit card and server is doing actual job using the tokenised string. It seems there is no way to implement this using this client SDK at this moment? Is there any work-around?

**Comment by stefan-sedlak** [comment]
Hi,

you can use transaction types:
-  [authorization-only](https://github.com/wirecard/paymentSDK-iOS/blob/b60ff5b4ec053637861624c64a57a4b730be4b62/eCom/WDeCom.framework/Headers/WDECTransactionType.h#L30) to validate card with issuer or
- [tokenize](https://github.com/wirecard/paymentSDK-iOS/blob/b60ff5b4ec053637861624c64a57a4b730be4b62/eCom/WDeCom.framework/Headers/WDECTransactionType.h#L86) to just save card

**Comment by yfujiki** [comment]
Thank you for the quick response! @stefan-sedlak
