### ISSUE TITLE
Perform payment and tokenize card

### ISSUE THREAD

**Issue by Gray-Wind** [wirecard/paymentSDK-iOS#24]
Is it possible to make a purchase and tokenize card in a single transaction?

There are different types of transactions `WDECTransactionTypePurchase` and `WDECTransactionTypeTokenize`.

In XML going from SDK I can see `merchant-tokenization-flag` set to `false`. Is it possible to set it to `true`?

**Comment by stefan-sedlak** [comment]
Hi @Gray-Wind ,
you can set [tokenUsageIndicator](https://wirecard.github.io/paymentSDK-iOS/api/latest/Classes/WDECCardPayment.html#//api/name/tokenUsageIndicator) in WDECCardPayment to `YES`
Best,
Stefan

**Comment by Gray-Wind** [comment]
Thank you!

BTW, there is typo. Getter is called `istokenIndicatorUsed`, should be `isTokenIndicatorUsed`.
