### ISSUE TITLE
Add Support for Mac Catalyst 

### ISSUE THREAD

**Issue by diederich** [wirecard/paymentSDK-iOS#25]
The SDK contains a bunch of binary frameworks which are not compiled for the x86_64-maccatalyst architecture which is necessary to support Mac Catalyst (formerly UIKit for Mac).

Is resolving this in the pipeline?

**Comment by stefan-sedlak** [comment]
Hi @diederich no plans for mac. I will check how big effort it is and I will talk with product management. thanks for the idea.

**Comment by diederich** [comment]
Thanks @stefan-sedlak. I looked through the repo and the SDK looks pretty neat. If there are no other binary dependencies, it might be just flipping a switch / delivering XCFrameworks. 

We're currently using Braintree, but there's no support planned (https://github.com/braintree/braintree_ios/issues/479), so we're actively looking for alternatives.

🙏🙏🙏

**Comment by stefan-sedlak** [comment]
@diederich We use no 3rd party binaries in core/card frameworks. Maybe we can enable it just for core/card frameworks. I guess you do not need card scanner on desktop 😄

**Comment by diederich** [comment]
Sounds fantastic! And yes, that would be a big step forward, thank you for considering!
