### ISSUE TITLE
Cannot connect to production environment

### ISSUE THREAD

**Issue by yfujiki** [wirecard/paymentSDK-iOS#28]
I have modified the Swift sample code to work with `.tokenize` request with our test environment.

```
        payment.amount = AMOUNT
        payment.currency = "USD"
        payment.transactionType = .tokenize
        let WD_MERCHANT_ACCOUNT_ID = "XXXXXXXXXXX"
        let WD_MERCHANT_SECRET_KEY = "YYYYYYYYYYY"
```

The code runs successfully and returns tokenised card response just fine.

However, after I change the `WD_MERCHANT_ACCOUNT_ID` and `WD_MERCHANT_SECRET_KEY` to production ones we received, I get unauthorised error.

```
Error Domain=com.wirecard.error Code=-3 "Transaction has failed" UserInfo={NSLocalizedDescription=Transaction has failed, NSUnderlyingError=0x6000022820d0 {Error Domain=com.alamofire.error.serialization.response Code=-1011 "Request failed: unauthorized (401)" UserInfo={NSLocalizedDescription=Request failed: unauthorized (401), NSUnderlyingError=0x600002282970 {Error Domain=com.alamofire.error.serialization.response Code=-1016 "Request failed: unacceptable content-type: text/plain" UserInfo={NSLocalizedDescription=Request failed: unacceptable content-type: text/plain, NSErrorFailingURLKey=https://api.wirecard.com/engine/mobile/v2/payments, com.alamofire.serialization.response.error.data={length = 39, bytes = 0x436f756c 64206e6f 74207265 74726965 ... 72657420 6b65792e }, com.alamofire.serialization.response.error.response=<NSHTTPURLResponse: 0x600002c40340> { URL: https://api.wirecard.com/engine/mobile/v2/payments } { Status Code: 401, Headers {
    "Content-Length" =     (
        39
    );
    Date =     (
        "Wed, 11 Dec 2019 03:44:23 GMT"
    );
    Server =     (
        ""
    );
    "Strict-Transport-Security" =     (
        "max-age=16070400; includeSubDomains"
    );
}
```

If you wonder, I have changed the environment of the `WDECClient` to `PROD` as well, and I can see that the request is going to `api.wirecard.com` instead of `api-test.wirecard.com`.

```
self.client = WDECClient.init(environment: WDECEnvironment.PROD)!
```

Our Android counter part succeeded to connect to production environment with the same `MERCHANT_ACCOUNT_ID` and `MERCHANT_SECRET_KEY`, so the issue is not about the wrong keys etc. 

One notable thing is that our Android counter part using Android SDK is connecting to `api1.wirecard.com` instead of `api.wirecard.com`. 

Can you guys help me out on this? I totally expected that switching from TEST to PROD is just switching the account id and secret. (which worked on Android end...)

Thank you

**Comment by stefan-sedlak** [comment]
Hi @yfujiki ,

Your expectation is correct just `WDECEnvironment.PROD` uses `api.wirecard.com` hostname.

As you need to connect to `api1.wirecard.com` gateway you can use `WDECClient` [initializer](https://github.com/wirecard/paymentSDK-iOS/blob/53a035dd454a817297466ce4986cb1a2893a8490/eCom/WDeCom.framework/Headers/WDECClient.h#L60) with hostname.

`WDECEnvironment` will be deprecated because hostnames provide flexibility.

Best,
Stefan

**Comment by yfujiki** [comment]
Thank you @stefan-sedlak It worked like a charm!
