### ISSUE TITLE
When closing dialogs, Wirecard dismisses app's modal ViewControllers

### ISSUE THREAD

**Issue by TheStalwart** [wirecard/paymentSDK-iOS#30]
Any time Wirecard presents its own dialogs, e.g. adding a new card or going through secure3d, it dismisses not only its own dialogs, but app's entire ViewController stack down to root ViewController.

This has been discovered after migrating the project to Xcode 11, and not reproducible on iOS 12 devices.

**Comment by stefan-sedlak** [comment]
Hi @TheStalwart ,
our implementation has not changed. SDK always switches rootViewController. When payment is finished original rootViewController is restored.

Could you please provide:
- SDK version
- iOS version
- steps (code snippet) how to reproduce the issue.

Thanks,
Stefan

**Comment by TheStalwart** [comment]
Behavior of modal ViewControllers has changed in iOS SDK 13 / Xcode 11. The same code works in a different way now.

When Wirecard presents e.g. a new card form, on iOS 12 device the Wirecard VC and app's VC that presented it are on the same stack, but on iOS 13 device Wirecard creates a new UIWindowScene stack. The problem we experience is that Wirecard is the third UIWindowScene stack of our app, and upon dismiss, it restores the 1st Scene stack with app's welcome screen instead of 2nd Scene that initially called Wirecard.

SDK: Xcode 11.3
iOS: 13.3 (not reproducible on 12.3.1)

Steps to reproduce:
1. Create a "Welcome" UIViewController
2. Present a "Business" UIViewController modally
3. Call Wirecard SDK in a way that presents a modal dialog e.g. "New Card"
4. Dismiss it -> You're back to "Welcome" UIViewController
5. Try the same code, same SDK, but on iOS 12 device - works as expected

**Comment by stefan-sedlak** [comment]
Hi @TheStalwart 
I still miss paymentSDK version :)
Thanks,
Stefan

**Comment by TheStalwart** [comment]
@stefan-sedlak we use 3.8.0

**Comment by stefan-sedlak** [comment]
Thanks for additional information, meanwhile we started investigation.
Do you collect card data via WDEC(Animated)CardField or via SDK VC ?
Thanks,
Stefan

**Comment by TheStalwart** [comment]
ViewDebugger states it's WDECCardPaymentScannerGalleryVC whose dismissal triggers the issue.

We call it in the following way:
wdecPaymentManager.getPaymentSignature(payment: payment)

**Comment by stefan-sedlak** [comment]
Hi @TheStalwart ,
still I miss information how do you collect card data?
- explicitly by [WDECCardField](https://wirecard.github.io/paymentSDK-iOS/api/3.8.0/Classes/WDECCardField.html) / [WDECAnimatedCardField](https://wirecard.github.io/paymentSDK-iOS/api/3.8.0/Classes/WDECAnimatedCardField.html) or
- implicitly by SDK -\[WDECClient [makePayment:withCompletion:](https://wirecard.github.io/paymentSDK-iOS/api/3.8.0/Classes/WDECClient.html#//api/name/makePayment:withCompletion:)\]
?

Thanks,
Stefan

**Comment by TheStalwart** [comment]
The second option:
client.make(payment, withCompletion:)

**Comment by stefan-sedlak** [comment]
Thanks! We are working on it. I will keep you updated.

**Comment by stefan-sedlak** [comment]
Hi @TheStalwart ,
the issue is caused by incompatible Apple change.
We will provide workaround by using `UIWindow`.
It is compatible but quite big change so we will release the change in 4.0.0.
4.0.0 will require signature v2. Deprecated signature v1 will be removed.
Best,
Stefan

**Comment by stefan-sedlak** [comment]
Hi @TheStalwart ,
the fix was published. Sry for delay.
BEst,
Stefan

**Comment by TheStalwart** [comment]
The issue is not fixed, it's just broken in a different way now. Previously, WDECClient was nuking the entire modal dialog stack, now the first two are preserved, but the rest of the stack is still wiped.

**Comment by stefan-sedlak** [comment]
Hi @TheStalwart ,
paymentSDK itself does not close any modal dialog. Apple SDK does.

Could you please provide more details how 4.0.0 release affects your app?

Thanks,
Stefan

**Comment by TheStalwart** [comment]
I'm actually very busy working on other features of the app now. I tested it this morning because i hoped it's just a matter of pod update since i migrated the app to signature v2 a while ago.

This issue is on my priority list however, so expect feedback later.
