### ISSUE TITLE
After upgrade to 3.8.0 from 3.2 we don't receive IPN anymore

### ISSUE THREAD

**Issue by alex-parp** [wirecard/paymentSDK-iOS#31]
Hello.

After upgrading to 3.8.0 we don't receive the IPN anymore. We execute a creditcard payment, we didn't change the fields we set on the payment request but after the upgrade we don't receive the IPN anymore. We tested using the old version (3.2) for which we receive the IPN.

We set the following fields on the payment request :
- transactionType
- amount
- currency
- locale
- notifications array (1 notification with the url to our server)
- signature
- merchantAccountId
- requestId

Thank you for the support,
Alex

**Comment by stefan-sedlak** [comment]
Hi @alex-parp ,
we will investigate the issue ASAP.
If you need to update urgently you can ask merchant support for IPN configuration for you merchant account (in case of static URLs).
Best,
Stefan

**Comment by stefan-sedlak** [comment]
Hi @alex-parp ,
paymentSDK incorrectly requires optional IPN [notificationFormat](https://github.com/wirecard/paymentSDK-iOS/blob/3.8.1/eCom/WDeCom.framework/Headers/WDECPayment.h#L122) property. You can use one of these format [values](https://github.com/wirecard/paymentSDK-iOS/blob/3.8.1/eCom/WDeCom.framework/Headers/WDECNotificationFormat.h#L20-L21) in releases <= 3.8.1 .

Fix will be released in 3.8.2 .
I advise to migrate to signature v2 as signature v1 will be removed in release 4.0.0

Best,
Stefan
