### ISSUE TITLE
Implementation in React Native for Mobile Apps

### ISSUE THREAD

**Issue by ParvendraSingh** [wirecard/paymentSDK-iOS#32]
Hi,
How can i use WireCard Payment  Gateway for Mobile Apps in React Native ?
Suggest me if there any way to implementation for React native.

**Comment by stefan-sedlak** [comment]
Hi @ParvendraSingh ,

there is no official ReactNative SDK.
We can provide you support to wrap our Android / iOS SDKs to ReactNative.
But we are not sure if it is feasible.

We are not ReactNative developers so we cannot advise you.

Best,
Stefan
