### ISSUE TITLE
Using AFNetwork and Apple will block from submit after April 1

### ISSUE THREAD

**Issue by felipeflorencio** [wirecard/paymentSDK-iOS#33]
Your SDK is using a very old library as dependency, AFNetwork, that uses UIWebView, and Apple will block from submit / accept any app that has this in the binary.

Basically i'm stuck if use your SDK were is the fix?

This is from Apple:

ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of new apps that use UIWebView APIs starting from April 2020. See https://developer.apple.com/documentation/uikit/uiwebview for more information.

And as you use AFNetworking that uses this UIWebView, anyone that uses your library will be stuck.

**Comment by stefan-sedlak** [comment]
Hi @felipeflorencio ,
we already have the task on TODO list.
It will be released in next release.
Best,
Stefan

**Comment by stefan-sedlak** [comment]
Hi @felipeflorencio 
please check release [4.1.0](https://github.com/wirecard/paymentSDK-iOS/releases/tag/4.1.0)
