### ISSUE TITLE
ApplePay issue

### ISSUE THREAD

**Issue by alex-parp** [wirecard/paymentSDK-iOS#36]
Hello.

We're having problems making ApplePay work. We're using the latest 4.1 release.

When we select applepay the ApplePay ui opens with the selected sum, however when we click on purchase we get the following error :
![image](https://user-images.githubusercontent.com/59737703/80404533-fe089200-88c9-11ea-870c-3a3bb80677f0.png)

Can you please advise what's wrong. Also can you point me to the list of error codes the SDK returns.

Thank you,
Alex

**Comment by PeterStavny** [comment]
Hi Alex,

Can you send me please additional information?
- device/simulator?
- endpoint PROD/TEST?
- do you have Apple Merchant ID (Apple Developer Portal) and do you setup Certificate Signing Request (csr-file generated by the Merchant support)? 

Thanks
Peter

**Comment by alex-parp** [comment]
Hello.

We tested on device. On simulator it doesn't work.

We're using the TEST SYSTEM.

Yes we have an apple merchant id and we created the Apple Pay Payment Processing Certificate using the CSR provided by Wirecard.

We're using the code :

	payment = new WDECApplePayManagedPayment();
	payment.TransactionType = WDECTransactionType.Purchase;
	(payment as WDECApplePayManagedPayment).AppleMerchantID = "<our_merchant_id>";
	(payment as WDECApplePayManagedPayment).MerchantCountry = WDECCountry.De;

Thanks,
Alex

**Comment by stefan-sedlak** [comment]
Hi @alex-parp ,
we need to investigate transaction.
Could you please provide us:

- hostname used to initialize `WDECClient`,
- merchant account identifier,
- requestId and
- transactionId, timestamp from response

Thanks,
Stefan

**Comment by stefan-sedlak** [comment]
Hi @alex-parp please reopen the issue if you need to continue investigation

**Comment by alex-parp** [comment]
![image](https://user-images.githubusercontent.com/59737703/83406158-b6b87880-a416-11ea-876e-fb885ddd0bb7.png)

RequestId :"61809135-CBED-402C-969E-69D9992B8802"
Response : 
400.1425 : Unable to decrypt cryptogram. Merchant account might not be configured properly. Please, contact technical support.
Transaction status : failed
Transaction id : null

If you need the payment.MerchantAccountID and it’s safe to post here, I can post it here.
Please let us know if we can do anything else.

**Comment by stefan-sedlak** [comment]
Hi @alex-parp it seems to me as apple merchant id misconfiguration.
to verify it please drop me ✉️ stefan.sedlak [at] wirecard.com
with your apple merchant id.
Thanks,
Stefan
