### ISSUE TITLE
I have the same issue, but I cannot update AFNetworking for some reason:

### ISSUE THREAD

**Issue by PeterStavny** [wirecard/paymentSDK-iOS#37]
I have the same issue, but I cannot update AFNetworking for some reason:

```
[!] CocoaPods could not find compatible versions for pod "AFNetworking/Serialization":
  In Podfile:
    paymentSDK/Core (~> 4.1.0) was resolved to 4.1.0, which depends on
      AFNetworking/Serialization (~> 3.2.1)
```

_Originally posted by @Gray-Wind in https://github.com/wirecard/paymentSDK-iOS/issues/35#issuecomment-623964729_

**Comment by PeterStavny** [comment]
Hi IIia, 

t's seems that you use different version of AFNetworking in your project's pod (I expect latest - 4.0.1). Currently paymentSDK uses the version 3.2.1. 

If you don't need updated AFNetworking framework with higher version please set mentioned version 3.2.1 for your project.

We'll update AFNetworking version in next release.

Thanks,
Peter

**Comment by Gray-Wind** [comment]
3.2.1 is still contains UIWebView, which is deprecated, so the issue remains on publishing of build.

**Comment by PeterStavny** [comment]
Do you use the AFNetworking dependecies? Can you please verify your podfile.lock and the AFNetworking dependecies? It should by there only:

AFNetworking/NSURLSession (~> 3.2.1)
AFNetworking/Reachability (~> 3.2.1)
AFNetworking/Security (~> 3.2.1)
AFNetworking/Serialization (~> 3.2.1).

and do you use only paymentSDK subspec by comment in [#35](https://github.com/wirecard/paymentSDK-iOS/issues/35#issuecomment-617847483)?

Peter

**Comment by Gray-Wind** [comment]
I use `AFNetworking` in my project and I was trying to update dependency by requiring version 4 to get rid of this deprecation notice.

**Comment by PeterStavny** [comment]
As you mentioned problem is GoogleMobileVision. 
We are not able to avoid this library or avoid only the specific subspec. But this framework is provided by the WdeComScanner framework only. 
To avoid the "UIWebView" issue I recommend you avoid modules with the WdeComScanner framework dependecy for now - let say a "quick solution". 

You are able to do it by podfile change (use instead pod 'paymentSDK'):

>     pod 'paymentSDK/Core', '~> 4.1.0'
>     pod 'paymentSDK/CoreCard', '~> 4.1.0'
>     pod 'paymentSDK/ApplePay', '~> 4.1.0'
>     pod 'paymentSDK/Card', '~> 4.1.0'
>     pod 'paymentSDK/PayPal', '~> 4.1.0'
>     pod 'paymentSDK/SEPA', '~> 4.1.0'
>     pod 'paymentSDK/ZAPP', '~> 4.1.0'
> 

If you use classes with WDEC.......ScannerGallery in your code you shall remove the postfix ScannerGallery. You will lost the scanner functonality of course.

**Comment by Gray-Wind** [comment]
I did not mention `GoogleMobileVision`. Right now my `Podfile` looks similar to this:

```
...
  pod 'AFNetworking', '~> 4'
  pod 'paymentSDK/Core', '~> 4.1.0'
  pod 'paymentSDK/CoreCard', '~> 4.1.0'
  pod 'paymentSDK/Card', '~> 4.1.0'
...
```

With `  pod 'AFNetworking', '~> 4'` it could not resolve dependency properly as `paymentSDK/Core` depends on `3.2.1`.

**Comment by PeterStavny** [comment]
As a fast solution you need to change

```
pod 'AFNetworking', '~> 4' 
```
 to:
```
pod 'AFNetworking', '~>  3.2.1', :subspecs => ['Reachability', 'Serialization', 'Security', 'NSURLSession'']
```
(those subspecs of AFNetworking are without UIWebView dependency). 

We'll update AFNetworking version in next release.

**Comment by Gray-Wind** [comment]
Thank you, hope to see next version soon 👍

**Comment by PeterStavny** [comment]
Hi, new version is available
