### ISSUE TITLE
AFNetworking.AFURLRequestSerialization requestWithMethod URLString nil and hard crash

### ISSUE THREAD

**Issue by ashcarr92** [wirecard/paymentSDK-iOS#38]
Edit: Apologies, this appears to be an issue with how we are signing the requests. I managed to take the code from the example and get it working. Now I'll begin investigation in to the signing issue.

**Comment by stefan-sedlak** [comment]
Hi @ashcarr92 ,
did you solve the issue or can I help?
Stefan

**Comment by ashcarr92** [comment]
Hi @stefan-sedlak 

Thanks for your reply. Yes, I discovered that the issue was related to signing. I took the demonstration code from this repo and managed to get it working in React Native.

This now allows me to move on to troubleshoot our server-side mechanism.
