### ISSUE TITLE
PaymentSDK with iOS 13.5.1

### ISSUE THREAD

**Issue by am9r** [wirecard/paymentSDK-iOS#39]
Hello,

during tests we found out that the SDK was not working, when we were using devices with iOS 13.5.1, however it worked without a problem, when we used devices with iOS version < 13.5.

Is there a know issue or are we missing something here.

best regards

**Comment by stefan-sedlak** [comment]
Hi @am9r ,
could you please describe your issue?
what SDK version do you integrate?
Thanks,
Stefan

**Comment by am9r** [comment]
so basically, wer are using the sdk version in 4.2 and the options to perform payment via credit card and payment via sepa. However our testers could not perform the payment on device with iOS 13.5.1. The payment screen just was not staring. The console logs, were not showing anything relevant

**Comment by stefan-sedlak** [comment]
did you include only card/sepa subspecs/frameworks or did you add others?
Can you list paymentSDK subspecs from your Podfile.lock ?

**Comment by am9r** [comment]
I added all, anyway here is my podfiel.lock

`- paymentSDK/All (4.2.0):
    - paymentSDK/ApplePay
    - paymentSDK/Card
    - paymentSDK/PayPal
    - paymentSDK/SEPA
    - paymentSDK/ZAPP
  - paymentSDK/ApplePay (4.2.0):
    - paymentSDK/CoreCard
  - paymentSDK/Card (4.2.0):
    - paymentSDK/CoreCard
  - paymentSDK/Core (4.2.0):
    - AFNetworking (~> 4.0.1)
    - CocoaLumberjack (~> 3.6.1)
    - libextobjc/EXTScope (~> 0.6.0)
    - Lockbox (~> 3.0.6)
    - Mantle (~> 2.1.1)
    - MBProgressHUD (~> 1.2.0)
    - TPKeyboardAvoiding (~> 1.3.3)
  - paymentSDK/CoreCard (4.2.0):
    - paymentSDK/Core
  - paymentSDK/PayPal (4.2.0):
    - paymentSDK/Core
  - paymentSDK/SEPA (4.2.0):
    - IBAN (~> 1.0.0)
    - paymentSDK/Core
  - paymentSDK/ZAPP (4.2.0):
    - paymentSDK/Core
    - ZappMerchantLib (~> 1.1.2)`

**Comment by PrimoWebsoft** [comment]
I am also getting the same issue, Please respond if you are able to solve the issue.

**Comment by comanl** [comment]
Hi,
 
we are working on this. soon will post an update if iOS 13.5.1 is still required. Currently iOS 14.2 is the latest release.

Cheers,
Liviu

**Comment by comanl** [comment]
Please check our new artifact compiled with Xcode 12.2 / Swift 5.3

**Comment by comanl** [comment]
Our new artifact was compiled with Xcode 12.2 / Swift 5.3
