### ISSUE TITLE
Error running example project

### ISSUE THREAD

**Issue by VincentV89** [wirecard/paymentSDK-iOS#4]
Hi, I tried running the sample project as it is but it cant build/run. Could you advise on this please? Thanks.

![screen shot 2017-08-17 at 7 13 24 pm](https://user-images.githubusercontent.com/17560003/29409736-3625fca6-8380-11e7-818d-0ef59d7334ef.png)

<img width="935" alt="screen shot 2017-08-17 at 7 13 29 pm" src="https://user-images.githubusercontent.com/17560003/29409740-3925bcb6-8380-11e7-9707-80ac3e72866e.png">

**Comment by stefan-sedlak** [comment]
Hi,
I have updateted example Podfile.lock files.
Pull changes and `pod install` shall work again :)
Thanks for the notice.
