### ISSUE TITLE
*QUESTION* IPN HTTP Headers

### ISSUE THREAD

**Issue by ashcarr92** [wirecard/paymentSDK-iOS#40]
Hi team, we have a question regarding the IPN functionality of the payment gateway. 

I have read the [documentation](https://docs.wirecard.com/GeneralPlatformFeatures.html#GeneralPlatformFeatures_IPN) as well as [searching issues](https://github.com/wirecard/paymentSDK-iOS/issues?q=http+headers), and did not find any relevant information. Therefore I understand that it's likely your response will be "no", however I must ask just in case.

Is it possible for us to specify a set of HTTP headers that the IPN is to use when sending the notification to our servers? We have a unique authorisation implementation that requires certain HTTP headers be set in order to call our endpoints.

**Comment by stefan-sedlak** [comment]
Hi @ashcarr92 ,
configuring HTTP headers is unsupported.
you can configure just body content - JSON/XML.
Best,
Stefan

**Comment by ashcarr92** [comment]
Hi @stefan-sedlak 

Thank you very much for your extremely fast response! Ok, I thought as much.
