### ISSUE TITLE
Module compiled with Swift 4.2.1 cannot be imported by the Swift 5.3 compiler

### ISSUE THREAD

**Issue by UmerAfzal1** [wirecard/paymentSDK-iOS#43]
After adding in pod and build in xcode 12 showing  error 
"Module compiled with Swift 4.2.1 cannot be imported by the Swift 5.3 compiler: /Users/Desktop/Ios Apps/app/PaymentSDK.framework/Modules/PaymentSDK.swiftmodule/x86_64.swiftmodule"

**Comment by UmerAfzal1** [comment]
Can you Please provide solution i'm waiting your kind response.
Thanks

**Comment by comanl** [comment]
Hi,

we are working on this and soon will post an update. 

Cheers,
Liviu

**Comment by comanl** [comment]
Duplicate of #39

**Comment by comanl** [comment]
Please check our new artifact compiled with Xcode 12.2 / Swift 5.3
