### ISSUE TITLE
How can we get card holder name ?

### ISSUE THREAD

**Issue by patelgaurav4u** [wirecard/paymentSDK-iOS#5]
need to get cardholder name for save token

**Comment by stefan-sedlak** [comment]
Hi,
can you provide your use case? Do you use WDCardField?

**Comment by patelgaurav4u** [comment]
we use WDCardStyle
and tokenize card for save card info

**Comment by stefan-sedlak** [comment]
Sry, it is not supported now.
It will be added in next release.

I can not specify release date.
I will internally discuss it and try to provide dedicated release with only this enhancement.

**Comment by patelgaurav4u** [comment]
thanks @stefan-sedlak

**Comment by stefan-sedlak** [comment]
Hi @patelgaurav4u ,
2.17.1 provides cardholder in WDPaymentResponse's property accountHolder
Reopen issue, if it does not work for you.

**Comment by patelgaurav4u** [comment]
Hello, We have check with 3D Secure demo card 
Visa | 4012000300001003 | 01/2019 | 003 |  wirecard
 but not get customer name

**Comment by stefan-sedlak** [comment]
Hi, I tested version 2.17.1.
I attach screenshot - cardholder name is mapped to lastName property.

If you use generic test account cardholder shall be present.

Do you use signature v1?

![screen shot 2018-03-28 at 10 49 35](https://user-images.githubusercontent.com/5908540/38018663-d16b1846-3275-11e8-84e7-50aa401f75a7.png)

**Comment by patelgaurav4u** [comment]
we are follow your example code

**Comment by stefan-sedlak** [comment]
I will update Examples ASAP to use signature v2.
