### ISSUE TITLE
Error: "Transaction has failed" / Swift

### ISSUE THREAD

**Issue by djovanovski** [wirecard/paymentSDK-iOS#6]
I tried to make a payment trough paymentSDK and it gives me the following error when I try to submit the card data:

``
Optional(Error Domain=com.wirecard.error Code=-3 "Transaction has failed" UserInfo={NSLocalizedDescription=Transaction has failed, NSUnderlyingError=0x1c4a567d0 {Error Domain=com.alamofire.error.serialization.response Code=-1011 "Request failed: unauthorized (401)" UserInfo={NSLocalizedDescription=Request failed: unauthorized (401), NSUnderlyingError=0x1c4a57820 {Error Domain=com.alamofire.error.serialization.response Code=-1016 "Request failed: unacceptable content-type: text/plain" UserInfo={NSLocalizedDescription=Request failed: unacceptable content-type: text/plain, NSErrorFailingURLKey=https://api-test.wirecard.com/engine/mobile/v2/payments, com.alamofire.serialization.response.error.data=<5369676e 61747572 65206973 206e6f74 2076616c 69642e>, com.alamofire.serialization.response.error.response=<NSHTTPURLResponse: 0x1c042dbe0> { URL: https://api-test.wirecard.com/engine/mobile/v2/payments } { Status Code: 401, Headers {
    Connection =     (
        close
    );
    "Content-Length" =     (
        23
    );
    "Content-Type" =     (
        "text/plain; charset=UTF-8"
    );
    Date =     (
        "Tue, 24 Apr 2018 14:07:39 GMT"
    );
    "Strict-Transport-Security" =     (
        "max-age=16070400; includeSubDomains"
    );
} }}}
``

I am importing the SDK on my Swift project. Here is my source code:
``

     func makePayment() {
          let amount = NSDecimalNumber(value: 1.99 as Float)
          let payment = WDCardPayment(amount: amount, amountCurrency: .BGN, transactionType: .purchase)
          payment?.requestID = UUID().uuidString
          payment?.requestTimestamp = Date()
          payment?.merchantAccountID = MERCHANT_ACCOUNT_ID

          let dateformatter = DateFormatter()
          dateformatter.dateFormat = "yyyy-MM-dd'T'HH:mm:ssZZZZZ"
          let dateString = dateformatter.string(from: payment?.requestTimestamp ?? Date())

          let signature = self.serverSideSignatureCalculationV2(requestTimestamp: dateString,
                                                                requestID: UUID().uuidString,
                                                                merchantID: MERCHANT_ACCOUNT_ID,
                                                                transactionType: WDTransactionTypeGetCode(.purchase),
                                                                amount: amount.stringValue,
                                                                currency: payment?.currency ?? "",
                                                                IPAddress: payment?.ipAddress ?? "",
                                                                secretKey: SECRET_KEY)

          payment?.signature = signature

          if let payment = payment {
               let client = WDClient(environment: .TEST)
               client?.make(payment, withCompletion: { (response, error) in
                    guard error == nil else {
                         print(error)
                         print("Error \(error?.localizedDescription)")
                         return
                    }
                    guard let response = response else {
                         print("A really weird error")
                         return
                    }
                    print("Payment successfull \(response)")
               })
          }
     }
``

For the signature part I rewrite the code from the Obj-c sample from Github:
''

     func serverSideSignatureCalculationV2(requestTimestamp:String,requestID:String,merchantID:String,transactionType:String,amount:String,currency:String,IPAddress:String,secretKey:String) -> String{

          var params:[String] = []
          params.append("HS256")
          params.append("request_time_stamp=\(requestTimestamp)")
          params.append("merchant_account_id=\(merchantID)")
          params.append("request_id=\(requestID)")
          params.append("transaction_type=\(transactionType)")
          params.append("requested_amount=\(amount)")
          params.append("requested_amount_currency=\(currency)")

          let payload = params.joined(separator: "\n")

          let payloadBase64 = payload.data(using: String.Encoding.utf8)?.base64EncodedString()
          let nsstring = payloadBase64 as NSString?
          let hmacBase64 = nsstring!.hmac256(withKey: secretKey)

          if let payloadBase64 = payloadBase64, let hmacBase64 = hmacBase64 {
               let signature = [payloadBase64, hmacBase64].joined(separator: ".")
               return signature
          }
          return ""
     }
``

I am using test access data and credentials from: 
https://document-center.wirecard.com/display/PTD/Appendix+K%3A+Test+Access+Data+and+Credentials

``
private let MERCHANT_ACCOUNT_ID = "9105bb4f-ae68-4768-9c3b-3eda968f57ea"

private let SECRET_KEY = "d1efed51-4cb9-46a5-ba7b-0fdc87a66544"
``

**Comment by stefan-sedlak** [comment]
Hi @djovanovski ,
**no signature shall be generated/computed on mobile side**,
because it is very insecure to use SECRET KEY on mobile side.
There is no need to compute it in Swift (except development purposes until server side is implemented).

According your code: request_time_stamp shall be in UTC ended by 'Z' timezone
```
dateformatter.dateFormat = "yyyy-MM-dd'T'HH:mm:ss'Z'"
dateformatter.timeZone = TimeZone(abbreviation:"UTC")
```

I hope it will help you with.
If no please provide computed signature.

Best,
Stefan

**Comment by djovanovski** [comment]
Hi @stefan-sedlak ,
I know that the signature should be generated from the server and I will be getting it but for now I need to make this work with your test data.

I've changed my dateFormat and added a timezone as you suggested but still I am getting the same error as before.

Below is my signature:
``
signature = "SFMyNTYKcmVxdWVzdF90aW1lX3N0YW1wPTIwMTgtMDQtMjVUMDc6MTU6MzhaCm1lcmNoYW50X2FjY291bnRfaWQ9OTEwNWJiNGYtYWU2OC00NzY4LTljM2ItM2VkYTk2OGY1N2VhCnJlcXVlc3RfaWQ9NDJBQzE0MTgtQzBDQS00NjJDLUE4QzYtNjJFMjcxMDU4RjNCCnRyYW5zYWN0aW9uX3R5cGU9cHVyY2hhc2UKcmVxdWVzdGVkX2Ftb3VudD0xLjk5MDAwMDAwOTUzNjc0MjkxMgpyZXF1ZXN0ZWRfYW1vdW50X2N1cnJlbmN5PUJHTg==.xGowYhO1G+oBojye0CQPC8yOER31Jb+jkEr5/zs7geI="
``

And here is my dateString:
``
dateString = "2018-04-25T07:15:38Z"
``

Also I've noticed in your 'Simple' that you add NSExceptionDomains in your .plist file
``
	<dict>
		<key>NSExceptionDomains</key>
		<dict>
			<key>api-test.wirecard.com</key>
			<dict>
				<key>NSExceptionMinimumTLSVersion</key>
				<string>1.0</string>
				<key>NSExceptionRequiresForwardSecrecy</key>
				<false/>
				<key>NSIncludeSubdomains</key>
				<false/>
			</dict>
		</dict>
		<key>NSAllowsArbitraryLoads</key>
		<true/>
	</dict>
``

Should I do something like this also ?

**Comment by stefan-sedlak** [comment]
No need to tweak NSExceptionDomains, it would return connection error.
Connection was established because gateway returned HTTP status code 401.

I guess issue will be with amount (1.990000009536742912)
You can try to initialize amount via string or [mantissa and exponent](https://developer.apple.com/documentation/foundation/nsdecimalnumber/1416003-init)

**Comment by djovanovski** [comment]
Hi @stefan-sedlak,

I've added the amount via mantissa 

``let amount = NSDecimalNumber(mantissa: 199 ,exponent: -2,isNegative: false)``


Here is my pament method in full:

func makePayment() {

          let amount = NSDecimalNumber(mantissa: 199 ,exponent: -2,isNegative: false)
          let payment = WDCardPayment(amount: amount, amountCurrency: .USD, transactionType: .purchase)
          payment?.requestID = UUID().uuidString
          payment?.requestTimestamp = Date()
          payment?.merchantAccountID = MERCHANT_ACCOUNT_ID

          let dateformatter = DateFormatter()
          dateformatter.dateFormat = "yyyy-MM-dd'T'HH:mm:ss'Z'"
          dateformatter.timeZone = TimeZone(abbreviation:"UTC")

          let dateString = dateformatter.string(from: Date())

          let signatureSwift = self.serverSideSignatureCalculationV2(requestTimestamp: dateString,
                                                                     requestID: UUID().uuidString,
                                                                     merchantID: MERCHANT_ACCOUNT_ID,
                                                                     transactionType: WDTransactionTypeGetCode(.purchase),
                                                                     amount: amount.stringValue,
                                                                     currency: payment?.currency ?? "",
                                                                     IPAddress: payment?.ipAddress ?? "",
                                                                     secretKey: SECRET_KEY)

          payment?.signature = signatureSwift

          if let payment = payment {
               let client = WDClient(environment: .TEST)
               client?.make(payment, withCompletion: { (response, error) in
                    guard error == nil else {
                         print(error)
                         print("Error \(error?.localizedDescription)")
                         return
                    }
                    guard let response = response else {
                         print("A really weird error")
                         return
                    }
                    print("Payment successfull \(response)")
               })
          }
     }

And again no luck, it gives me the same error...

**Comment by stefan-sedlak** [comment]
please send full signature

**Comment by djovanovski** [comment]
``
signature = "SFMyNTYKcmVxdWVzdF90aW1lX3N0YW1wPTIwMTgtMDQtMjVUMDg6NTY6MjZaCm1lcmNoYW50X2FjY291bnRfaWQ9MzNmNmQ0NzMtMzAzNi00Y2E1LWFjYjUtOGM2NGRhYzg2MmQxCnJlcXVlc3RfaWQ9QjEwM0YwRDAtNkY1NC00RDlGLUFEODctOEQ0NDRFRDBBOTdGCnRyYW5zYWN0aW9uX3R5cGU9cHVyY2hhc2UKcmVxdWVzdGVkX2Ftb3VudD0xLjk5CnJlcXVlc3RlZF9hbW91bnRfY3VycmVuY3k9VVNE.2c71j9qzFfZu+ReaYJU4BL+9tEQ/dzs7K48Ij5vrm+A="
``

generated 1 min ago

**Comment by stefan-sedlak** [comment]
In request I see another merchantAccountID as you sent above.
Do you use proper combination MAID + Secret Key?

**Comment by djovanovski** [comment]
Yes, sorry I tried to change them to see if it was prior to the merchant and secret test keys but nothing worked.

MAID = "9105bb4f-ae68-4768-9c3b-3eda968f57ea"
SecretKey = "d1efed51-4cb9-46a5-ba7b-0fdc87a66544"

signature = "SFMyNTYKcmVxdWVzdF90aW1lX3N0YW1wPTIwMTgtMDQtMjVUMDk6MDc6NTFaCm1lcmNoYW50X2FjY291bnRfaWQ9OTEwNWJiNGYtYWU2OC00NzY4LTljM2ItM2VkYTk2OGY1N2VhCnJlcXVlc3RfaWQ9MjM5NEFFRUEtNkZBNC00RjQzLTkwREYtNDk4MTlDMzk4OEQ4CnRyYW5zYWN0aW9uX3R5cGU9cHVyY2hhc2UKcmVxdWVzdGVkX2Ftb3VudD0xLjk5CnJlcXVlc3RlZF9hbW91bnRfY3VycmVuY3k9VVNE.GcWfZqgZDV0BsvOsBsA1FcRI8dIPOAjidTvNgSgJFz4="

Generated 1 min ago

**Comment by stefan-sedlak** [comment]
I think I found it.
payload.data(using: String.Encoding.utf8) shall be used for HMAC256 and no its base64 value

**Comment by djovanovski** [comment]
Even thought I am getting the signature from the server now, it doesn't work.

Do you have a working project with Swift, have you made it at least one that works with Swift ?

**Comment by stefan-sedlak** [comment]
@jozefVrana provided Swift example here: https://github.com/wirecard/paymentSDK-iOS/tree/master/Example-Swift
Best,
Stefan

**Comment by djovanovski** [comment]
Thanks @jozefVrana and @stefan-sedlak.

However I managed to make my Swift project work with real data from the server the day before you upload the Swift example.

If someone else encounters same issues make sure you run the payment on a separate thread, also double check the 'signature' and 'timestamp'(getting them from the server with the right format made it work).

Best, Darko

**Comment by stefan-sedlak** [comment]
@djovanovski Thread issue is a little bit strange, because SDK handles UI on main thread and network on bg threads
