### ISSUE TITLE
iPhone X top bar layout issue

### ISSUE THREAD

**Issue by TMGoyani** [wirecard/paymentSDK-iOS#8]
![simulator screen shot - iphone x - 2018-05-09 at 18 46 48](https://user-images.githubusercontent.com/38997991/39816608-5efe33f0-53b9-11e8-92ce-807700e938db.png)

**Comment by stefan-sedlak** [comment]
Thx for the report!
We will try to reproduce the issue and fix it.
Best,
Stefan

**Comment by stefan-sedlak** [comment]
Fixed in [2.17.4](https://github.com/wirecard/paymentSDK-iOS/releases/tag/2.17.4) .
Thanks,
Stefan
